### ISSUE TITLE
Config.JobsThatCanImpound

### ISSUE THREAD

**Issue by SATTAGAMES** [XxFri3ndlyxX/esx_impound#1]
I'm like a cop he says I can not use the / impound command
I'm only getting it when I'm a mechanic.

Would you help me??

**Comment by XxFri3ndlyxX** [comment]
Usually this happen when you restart resource. Restart server then try again.  If this still persist then show me you job database where it shows police

**Comment by XxFri3ndlyxX** [comment]
Also show job grade of police

**Comment by SATTAGAMES** [comment]
I have this error in F8
http://prntscr.com/myxjdw
police = grade 0

**Comment by SATTAGAMES** [comment]
Thanks for the support.

**Comment by XxFri3ndlyxX** [comment]
Try this version
[esx_impound.zip](https://github.com/XxFri3ndlyxX/esx_impound/files/2974745/esx_impound.zip)
Let me know if this fixes it so that i can update it.

**Comment by SATTAGAMES** [comment]
I have no error in F8 with this version that sent me.
But I still can not apprehend the car as a police officer.

**Comment by XxFri3ndlyxX** [comment]
Alright well it's really late here. I'm heading to bed and will have a look tomorrow.

**Comment by XxFri3ndlyxX** [comment]
Well i went and try and works fine the way it was so i reverted the change. The error you receive the first time is because you don't set proper job name. 
Database job table.
![Untitled](https://user-images.githubusercontent.com/18711345/54491960-ebcfbe00-4898-11e9-84c9-52264058833c.png)

config
-- The jobs that are able to impound vehicles
Config.JobsThatCanImpound = {'police', 'mechanic'}

The word need to be worder exactly how it is in database.

**Comment by SATTAGAMES** [comment]
Good Morning
I did again donwload after reading about what you said to have updated script again
More still encounter problems in using it I do not know why it only recognizes the mechanic work to apprehend the vehicle, the image shows my database of jobs esx
http://prntscr.com/mz29qi

**Comment by XxFri3ndlyxX** [comment]
Good morning to you too. I do not know what to tell you. Unfortunately i am clueless.  This is exactly what i use on my server and works perfectly.
[esx_impound.zip](https://github.com/XxFri3ndlyxX/esx_impound/files/2975287/esx_impound.zip)
If that does not work then you most likely have some scripts overriding it or some sort. I am just a noob coder so it's really hard to help you. I try my best. But nothing worked. 
Try this and show me exactly what you modify in config file.  so copy and past the config.lua once modified.
also screenshot of job grade as well where it say police and mecano.

**Comment by XxFri3ndlyxX** [comment]
Also another thing you can try is to load esx_impound after all jobs.

**Comment by XxFri3ndlyxX** [comment]
### JOBS ###
start esx_JobWhitelisting
start esx_jobs
start esx_policejob
start esx_ambulancejob
start esx_duty
start esx_taxijob
start esx_mechanicjob
start esx_impound

**Comment by SATTAGAMES** [comment]
Thank you for always responding to your support and very good ..
I have made progress in using it after your explanations.
Now error in F8 regarding it checking which job I'm at when starting the server.
As I entered the server as a mechanic he did not accept me to seize the vehicle, I set myself up as a police officer and it worked normally.
After I got back on the mechanic I was able to seize the vehicle ..
You may have noticed that I use google translator. I'm Brazilian and my English is not there, these things ... Sorry.
http://prntscr.com/mz2kv5

**Comment by SATTAGAMES** [comment]
It really is having problem in the part that it checks your job when you start the server.
local currentJob = 'unemployed'
ai na le le line 40
currentJob = ESX.GetPlayerData (). job.name
And the seize command will only work if you set yourself back on the job. police or mechanic

**Comment by XxFri3ndlyxX** [comment]
Yes i understand. But its hard to make this work for you when it works fine for me. I've been trying different things but it breaks the script. My skills are limited. Looking through other scripts to see how they do and if i can adapt there method. No promise that i can fix it tho.

**Comment by XxFri3ndlyxX** [comment]
[esx_impound.zip](https://github.com/XxFri3ndlyxX/esx_impound/files/2975380/esx_impound.zip)
Try this

**Comment by XxFri3ndlyxX** [comment]
nevermind this break the scripts.

**Comment by SATTAGAMES** [comment]
You have no error in F8 when you enter the server in the job police or mechanic?
On client / main line 40

**Comment by SATTAGAMES** [comment]
Do you get no error in F8 when you enter the server as police or mechanic?
At line 40 of client / main
where does he check his job?

**Comment by XxFri3ndlyxX** [comment]
Nope never It works 100 % Whatever way i do it. Log in as a cop then impound works. Change to mechanic then works then go back to police then works again. It simply never fails

**Comment by XxFri3ndlyxX** [comment]
Is your police version and mechanic up to date?

**Comment by XxFri3ndlyxX** [comment]
All my scripts are running latest version extended  essential police mechanic and so on. My guess is that something is not updated.

**Comment by SATTAGAMES** [comment]
police I'm using last edition, I'm going to upgrade mechanic, and see if it solves a problem

**Comment by XxFri3ndlyxX** [comment]
What about essential and extended? are they up to date?

**Comment by SATTAGAMES** [comment]
I upgraded all features
Essentialmode
es_extended
esx_police
esx_mechanic
But he can not recognize that I'm already on the job police or mechanic when I enter the server and the error in f8 regarding client / main line 40
the proplem that has to be set again in the job so that command / seize works.
I really wanted to use the script.

**Comment by XxFri3ndlyxX** [comment]
[esx_impound (2).zip](https://github.com/XxFri3ndlyxX/esx_impound/files/2975486/esx_impound.2.zip)
try this

**Comment by SATTAGAMES** [comment]
Thanks for trying to fix the script
I do not want to be taking your time if it works for you perfectly, just does not want to work for me.
Still he can not verify that I'm already at work police or mechanical when on the server.
And prevents you from using the command impound the vehicle

http://prntscr.com/mz54m7

**Comment by XxFri3ndlyxX** [comment]
Try this version
[esx_impound.zip](https://github.com/XxFri3ndlyxX/esx_impound/files/2975726/esx_impound.zip)

This should work altho it will be more cpu heavy than the version i use.
